### ISSUE TITLE
PydanticImportError

### ISSUE THREAD

**Issue by fredrikw** [nborrmann/diff-poetry-lock#12]
I just tried to run the action on one of our repos and got the following error:

```
/usr/bin/docker run --name b7370c3b4abee0ee4f8da7c714efdb723[9](https://github.com/IRLAB-Therapeutics/motron_camera_controller/actions/runs/8065907403/job/22032763135?pr=80#step:8:10)6b_879d3f --label 81b737 --workdir /github/workspace --rm -e "pythonLocation" -e "LD_LIBRARY_PATH" -e "INPUT_GITHUB_TOKEN" -e "INPUT_LOCKFILE_PATH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/motron_camera_controller/motron_camera_controller":"/github/workspace" 81b737:0c3b4abee0ee4f8da7c714efdb72396b
Traceback (most recent call last):
  File "/diff_poetry_lock/run_poetry.py", line [10](https://github.com/IRLAB-Therapeutics/motron_camera_controller/actions/runs/8065907403/job/22032763135?pr=80#step:8:11), in <module>
    from diff_poetry_lock.github import GithubApi
  File "/diff_poetry_lock/github.py", line 5, in <module>
    from diff_poetry_lock.settings import Settings
  File "/diff_poetry_lock/settings.py", line 4, in <module>
    from pydantic import BaseSettings, Field, ValidationError, validator
  File "/usr/local/lib/python3.[11](https://github.com/IRLAB-Therapeutics/motron_camera_controller/actions/runs/8065907403/job/22032763135?pr=80#step:8:12)/site-packages/pydantic/__init__.py", line 374, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.6/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.6/u/import-error
```

Your Dockerfile doesn't specify the pydantic version on line 3, bringing in Pydantic 2.6.2 in my case, causing this error.

**Comment by fredrikw** [comment]
I just realized that this is fixed in the master...
